language: python
sudo: false
python:
  - "pypy"
  - "pypy3.3-5.2-alpha1"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
install:
  - pip install -U pytest
  - pip install coverage
  - pip install coveralls
  - pip install pytest-cov
  - python setup.py develop
script:
  py.test -v --cov tinydb_serialization
after_success:
  coveralls
